#infile='<tree_association.txt file generated by the predict.py script>'

infile='tree_association.txt'
#infile='/work/data/test_joona/Default/friendTrees/tree_association.txt'
from testing import makePlots_async

makePlots_async(infile,      #input file or file list
                ['test'],    #legend names (needs to be list)
                'jet_pt',    #variable to plot
                'jet_pt>40', #cut to apply
                'green',     #line color and style (e.g. 'red,dashed')
                'test.pdf',  #output file (pdf)
                'xaxis',     #xaxisname
                'yaxis',     #yaxisname
                False)       #normalize



makePlots_async(infile,      #input file or file list
                ['central','forward'],    #legend names (needs to be list)
                'jet_pt',    #variable to plot
                ['jet_eta<1.1 && jet_eta>-1.1','jet_eta<-1.1 || jet_eta>1.1'], #cut to apply
                ['green','red'],     #line color and style (e.g. 'red,dashed')
                'test2.pdf',  #output file (pdf)
                'xaxis',     #xaxisname
                'yaxis',     #yaxisname
                True)       #normalise

makePlots_async(infile,['B','C','UDS'],'(reg_Pt-gen_pt_WithNu)/gen_pt_WithNu',["isB+isBB+isLeptonicB+isLeptonicB_C &&  gen_pt_WithNu>30","isC &&  gen_pt_WithNu>30","isUD+isS+isG &&  gen_pt_WithNu>30"],['green','red','blue'],'resol.pdf','resol','jets',True)


makePlots_async(infile,['B','C','UDS'],'(reg_Pt-gen_pt_WithNu)/reg_uncPt',["isB+isBB+isLeptonicB+isLeptonicB_C &&  gen_pt_WithNu>30","isC &&  gen_pt_WithNu>30","isUD+isS+isG &&  gen_pt_WithNu>30"],['green','red','blue'],'pull.pdf','pull','jets',True)

makePlots_async(infile,['inclusive'],'(reg_Pt-gen_pt_WithNu)/gen_pt_WithNu',["gen_pt_WithNu>30"],['green'],'resol_incl.pdf','resol','jets',True)

makePlots_async(infile,['inclusive'],'(reg_Pt-gen_pt_WithNu)/reg_uncPt',["gen_pt_WithNu>30"],['green'],'pull_incl.pdf','pull','jets',True)

makePlots_async(infile,['inclusive'],'(reg_Pt-gen_pt_WithNu)/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30"],['green'],'resol_v_gen.pdf','gen Pt','resol',False)

#makePlots_async(infile,['inclusive'],'(reg_Pt-gen_pt_WithNu)/reg_uncPt:gen_pt_WithNu',["gen_pt_WithNu>30"],['COLZ'],'pull_v_gen.pdf','gen Pt','pull',False)

#makePlots_async(infile,['inclusive'],'(jet_corr_pt-gen_pt_WithNu)/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30"],['COLZ'],'resolcorPt_v_gen.pdf','gen Pt','resol (corPt)',False)


#profile plots
makePlots_async(infile, #input file or file list
                ['inclusive','B','C','UDS'], #legend names [as list]
                'reg_Pt/gen_pt_WithNu:gen_pt_WithNu', #variable to plot --> yaxis:xaxis
                ["gen_pt_WithNu>30&&gen_pt_WithNu<300","isB+isBB+isLeptonicB+isLeptonicB_C &&  gen_pt_WithNu>30&&gen_pt_WithNu<300","isC &&  gen_pt_WithNu>30&&gen_pt_WithNu<300","isUD+isS+isG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300"], #list of cuts to apply
                ['black','green','red','blue'], #list of color and style, e.g. ['red,dashed', ...]
                'resol_v_gen_Profile.pdf', #output file (pdf)
                'gen Pt', #xaxisname
                'response', #yaxisname
                False, #normalize
                "Mean", #make a profile plot - possible choices: "None" [Default, no profile] || "GaussFitMean"|| "GaussFitWidth"|| "GaussFitWidthNormByMean") || "GaussFitChi2" || "GaussFitProb" || "Mean"|| "StandardDeviationNormByMean"|| "StandardDeviation"|| "Median"|| "IQMean"
                0.7, #override min value of y-axis range
                1.3) #override max value of y-axis range

makePlots_async(infile,['inclusive','B','C','UDS'],'jet_corr_pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300","isB+isBB+isLeptonicB+isLeptonicB_C &&  gen_pt_WithNu>30&&gen_pt_WithNu<300","isC &&  gen_pt_WithNu>30&&gen_pt_WithNu<300","isUD+isS+isG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300"],['black','green','red','blue'],'resol_v_gen_Profile_Default.pdf','gen Pt','response',False,"Mean",0.7,1.3)


makePlots_async(infile,['inclusive','G','UDS'],'jet_corr_pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3","isPhysG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3","isUD+isS &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3"],['black','green','red'],'resol_v_gen_Profile_UDSvsG_BB_Default.pdf','gen Pt','response',False,"Mean",0.9,1.0)


makePlots_async(infile,['inclusive','G','UDS'],'jet_corr_pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=1.3&&TMath::Abs(jet_eta)<2.5","isPhysG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=1.3&&TMath::Abs(jet_eta)<2.5","isUD+isS &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=1.3&&TMath::Abs(jet_eta)<2.5"],['black','green','red'],'resol_v_gen_Profile_UDSvsG_EC_Default.pdf','gen Pt','response',False,"Mean",0.9,1.0)


makePlots_async(infile,['inclusive','G','UDS'],'jet_corr_pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=2.5&&TMath::Abs(jet_eta)<3.0","isPhysG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=2.5&&TMath::Abs(jet_eta)<3.0","isUD+isS &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=2.5&&TMath::Abs(jet_eta)<3.0"],['black','green','red'],'resol_v_gen_Profile_UDSvsG_EE_Default.pdf','gen Pt','response',False,"Mean",0.9,1.0)

makePlots_async(infile,['inclusive','G','UDS'],'jet_corr_pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=3.0&&TMath::Abs(jet_eta)<5.2","isPhysG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=3.0&&TMath::Abs(jet_eta)<5.2","isUD+isS &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=3.0&&TMath::Abs(jet_eta)<5.2"],['black','green','red'],'resol_v_gen_Profile_UDSvsG_HF_Default.pdf','gen Pt','response',False,"Mean",0.9,1.0)


#plot resolution
makePlots_async(infile,['inclusive','G','UDS'],'jet_corr_pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3","isPhysG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3","isUD+isS &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3"],['black','green','red'],'StdDevNormByMean_v_gen_Profile_UDSvsG_BB_Default.pdf','gen Pt','response',False,"StandardDeviationNormByMean",0.0,0.5)

makePlots_async(infile,['inclusive','G','UDS'],'reg_Pt/gen_pt_WithNu:gen_pt_WithNu',["gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3","isPhysG &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3","isUD+isS &&  gen_pt_WithNu>30&&gen_pt_WithNu<300&&TMath::Abs(jet_eta)>=0.0&&TMath::Abs(jet_eta)<1.3"],['black','green','red'],'StdDevNormByMean_v_gen_Profile_UDSvsG_BB_WithRegression.pdf','gen Pt','response',False,"StandardDeviationNormByMean",0.0,0.5)
